### ISSUE TITLE
Migrate Longhorn Infrastructure to CNCF

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1479]
This contains the tasks we want to do to migrate Longhorn infrastructure to CNCF.

- [x] Setup Rancher and Kubernetes cluster.
- [x] Run the upgrade responder and provide a dashboard to the public (to be done)
- [x] GitHub Runner (to be done)
- [x] Migrate Jenkins
- [x] Migrate Drone.

**Comment by yasker** [comment]
Done. We Will track issues separately.
