### ISSUE TITLE
Longhorn system backup and restore

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#3205]
To have a complete story for Longhorn system backup & restore. We need to consider the following scenarios:
- ECTD backup & restore
    - [x] Restore to a cluster that contains all volume data: 
            It's already done in https://github.com/longhorn/longhorn/issues/2228. And the instruction doc is in https://longhorn.io/docs/1.2.2/advanced-resources/rancher-cluster-restore/
    - [x] Restore to a brand new cluster that does not contain anything:
            There was one user that provided the instruction step: https://github.com/longhorn/longhorn/issues/2228#issuecomment-792750229
- Non-ECTD backup & restore
    - [ ] Restore to a cluster that contains all volume data: 
            There is already a possible way for this case: https://github.com/longhorn/longhorn/issues/3166#issuecomment-953804773. It works but is not perfect. We need to determine what we need to do next.
    - [ ] Restore to a brand new cluster that does not contain anything: 
            Velero + Restic may be a solution candidate. Or we can add a DR controller in the Longhorn backend that helps the restore.

**Comment by innobead** [comment]
Duplicated of https://github.com/longhorn/longhorn/issues/1455
