### ISSUE TITLE
[EPIC] Side effects of increasing resync period in informer's event handlers

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#3629]
We increased resync period in informer's event handlers from 30s to 1h at https://github.com/longhorn/longhorn-manager/pull/1210
```
	kubeInformerFactory := informers.NewSharedInformerFactory(kubeClient, time.Hour)
	lhInformerFactory := lhinformers.NewSharedInformerFactory(lhClient, time.Hour)
```
The idea is that our controllers should have correct informers' event handlers instead of relying on the resync period to cover up the mistakes.  The modification surfaces the hidden issues in our controller. This epic keeps track of those issues
- [x] https://github.com/longhorn/longhorn/issues/3626
- [x] https://github.com/longhorn/longhorn/issues/3620
- [x] https://github.com/longhorn/longhorn/issues/3678
- [x] https://github.com/longhorn/longhorn/issues/3692
- [x] https://github.com/longhorn/longhorn/issues/3679
- [x] https://github.com/longhorn/longhorn/issues/3070
- [x] https://github.com/longhorn/longhorn/issues/3821
- [x] https://github.com/longhorn/longhorn/issues/3820
- [ ] https://github.com/longhorn/longhorn/issues/3843

**Comment by PhanLe1010** [comment]
**A idea about refactoring replica creation/scheduling out of the volume controller**

This is related to the discussion at https://github.com/longhorn/longhorn/issues/3626. In the issue, we were discussing the issue of requeuing the volume CR if the volume doesn't have enough healthy replicas. While looking into the issue, I see an opportunity to refactor the replica creation/scheduling logic to be outside of the volume controller. This will be a step closer to our goal of [simplifying the volume controller](https://github.com/longhorn/longhorn/issues/2527) 

Currently, replica creation is inside the function [replenishReplicas](https://github.com/longhorn/longhorn-manager/blob/5f5fdc12adf9cf0467ed76fdb23676c2ca15f4f5/controller/volume_controller.go#L1564) and volume scheduling is inside [vc.scheduler.ScheduleReplica](https://github.com/longhorn/longhorn-manager/blob/5f5fdc12adf9cf0467ed76fdb23676c2ca15f4f5/controller/volume_controller.go#L1048). That logic will be run when volume controller sync loop runs.

The idea is to create a new controller to handle replica creation/scheduling. The new controller can just watch the volume CR (no need to create a new CRD) and try to create/delete/schedule a replica to move the current state closer to the desired state. If there is any error while syncing, we can consider 3 cases:
1. Cannot create new replica due to replenishment wait interval -> add the key back to the queue using `queue.AddAfter(key, duration)` where duration is the duration that we need to wait until it passes the replenishment wait interval
2. Cannot create new replica due to replica reused backoff ->  add the key back to the queue using `queue.AddAfter(key, duration)` where duration is the current backoff interval
3. Cannot schedule a replica -> add the key back using `queue.AddRateLimited(key)` 
4. Any general/temporary error -> add the key back using `queue.AddRateLimited(key)`

**Comment by innobead** [comment]
We will revisit this in 1.4.0.

**Comment by innobead** [comment]
@PhanLe1010 I believe you have made some efforts on this. Is there anything left we need to do? If not, let's close this.

**Comment by PhanLe1010** [comment]
We are still keeping the resync at 30s for some controllers for now but try our best effort on not to rely on it. The new controller should be designed so that it doesn't need resync at all (for example: volumeAttachment controller, snapshot controller, ...)

With this approach and since there is no side effect left, let's close this issue
