### ISSUE TITLE
[IMPROVEMENT] Consolidate volume attach/detach implementation

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#3715]
## Is your improvement request related to a feature? Please describe

There are several cases related to (auto) volume attach/detach, right now we leverage the volume attributes to achieve that, but it's better to introduce a new resource (longhorn volumeattachement) to have complete context for each scenario. 

## Describe the solution you'd like

This is an idea from https://github.com/longhorn/longhorn/issues/2527#issuecomment-951901533

## Describe alternatives you've considered

N/A

## Additional context

https://github.com/longhorn/longhorn-manager/pull/1037#issuecomment-1061642104
https://github.com/longhorn/longhorn/issues/2527

cc @shuo-wu @c3y1huang @PhanLe1010 @joshimoo 

Sub-issues:
- [x] https://github.com/longhorn/longhorn/issues/3692
- [x] Refactor auto attachment for recurring job
- [x] https://github.com/longhorn/longhorn/issues/3726
- [x] Refactoring auto attachment when volume is detach unexpectedly. This is a part of the ticket https://github.com/longhorn/longhorn/issues/2527#issuecomment-966597537

**Comment by joshimoo** [comment]
Here is an old PR where I explored the VA refactoring, this wasn't using a dedicated VA crd instead there was dedicated controllers per operation that would be managing desired attachment via setting `v.spec.NodeID` 

while the controller was utilizing `v.status.NodeID` to inform about attachment, there is some refactoring in there that should be applied to the volume controller indepedent of using a VA object. 

-------------

Have a look at the commit messages to see where I was going with this. Some of these have already been applied over time.
Like the csi driver having less and less logic instead having the attach call on the api making the decisions and checking all conditions.

- https://github.com/longhorn/longhorn-manager/pull/857/commits/22eff5d593d49bdc32e43a5852563114da9e95d9
- https://github.com/longhorn/longhorn-manager/pull/857/commits/8926c040e8dd8381ccfb10a05b7d87464d4268d0

-------------

This is the main part of the internal controller change:
- https://github.com/longhorn/longhorn-manager/pull/857/commits/2ac48fd936ee65fd4d9b37d445f76e698319e3a4

-------------

Using a dedicated VA resource to determine attachment seems reasonable, but we would need to think about it whether we want to have it per Node/User and we also need to consider reference counting for the VA, so that a system initiated action can also use the VA and not get cleaned up / clean up a user initiated action.

**Comment by PhanLe1010** [comment]
Adding @joshimoo as assignee as we are  co-working on this ticket

**Comment by PhanLe1010** [comment]
### TODO list for part-2 PR

- [ ]  UI modification to work with new AD mechanism (Longhorn UI -> Longhorn API)
- [ ] Fix unit test of AD and volume controller
- [ ] Consider how to upgrade from the previous Longhorn version which doesn't have VA resource yet 
    - [ ] Upgrade path for the new field `volume.Status.CurrentMigrationNodeID`
- [ ] Implement interrupt mechanism for higher priority attachment ticket
- [ ] Attachment creation and deletion functions are implemented in some controllers. We can probably make it reused by different controllers
- [ ] Test live migration on Harvester deployment 
- [ ] TODO: hadndle cases in which NodeID is empty. Should we detach the volume from all nodes???
- [ ] `func (m *VolumeManager) CreateSnapshotCR` is checking condition before creating the snapshot CR, perhaps this should be handle by webhook

**Comment by PhanLe1010** [comment]
# Test Plan
(In progress...)

## Attachment interruption
1. Create a 20GB PVC using `longhorn` StorageClass. Create a test deployment of 1 pod using the PVC.
2. Exec into the workload pod. Write 6GB of data into the volume's mount point using `dd`. Calculate the checksum of the new file.
3. Note down the `volume.status.ownerID`. Lets say it is `node-1`
4. Scale down the test deployment to detach volume. Edit the deployment YAML so that it will deploy pod on `node-2` when we scale up later.
5. Follow the instruction [here](https://longhorn.io/docs/1.4.2/snapshots-and-backups/csi-snapshot-support/csi-volume-snapshot-associated-with-longhorn-backup/) to create a CSI snapshot of type backup. Wait for the Longhorn backup to start.
6. Note that the backup controller creates a `backup-controller-xxx` ticket in the VolumeAttachment object of the volume (`kubectl get volumeattachments.longhorn.io -n longhorn-system <VOLUME-NAME>`). The ticket has `nodeID` set to `node-1`
7. While the backup is in-progress, scale up the test deployment.
8. Verify that:
    1. There is an `csi-attacher-xxx` ticket created for the workload pod inside Longhorn VolumeAttachment object. This ticket has `nodeID` set to `node-2`
    2. The `csi-attacher-xxx` ticket interrupt the `backup-controller-xxx`  so that workload pod doesn't have to wait for the backup to finish 
    3. Workload pod is able to start on `node-2`
    4. The in-progress backup failed
    5. The checksum of data matches the calculation above

**Comment by PhanLe1010** [comment]
## Test Upgrade 

### CSI flow

### Live migration
1. Deploy Longhorn older version v1.4.x
1. Create storageclass, PVC, and workload pod-1 as below
    ```
    kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: longhorn-migratable
    provisioner: driver.longhorn.io
    allowVolumeExpansion: true
    parameters:
      numberOfReplicas: "3"
      staleReplicaTimeout: "2880" # 48 hours in minutes
      fromBackup: ""
      migratable: "true"
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: longhorn-block-vol
      namespace: default
    spec:
      accessModes:
        - ReadWriteMany
      volumeMode: Block
      storageClassName: longhorn-migratable
      resources:
        requests:
          storage: 2Gi
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: pod-1
      namespace: default
    spec:
      nodeName: <NODE-1>
      containers:
        - name: block-volume-test
          image: ubuntu:xenial
          imagePullPolicy: IfNotPresent
          command: ["sleep", "36000"]
          volumeDevices:
            - devicePath: /dev/longhorn/testblk
              name: block-vol
      volumes:
        - name: block-vol
          persistentVolumeClaim:
            claimName: longhorn-block-vol
    ```
1. Exec into pod-1. Write some data `dd if=/dev/urandom of=dev/longhorn/testblk bs=1M count=100`. Caculate checksum `dd if=dev/longhorn/testblk bs=1M count=100 | md5sum`
1. Upgrade Longhorn to master-head
1. Deploy workload pod-2 to trigger live migration of volume to new node, NODE-2
    ```
    apiVersion: v1
    kind: Pod
    metadata:
      name: pod-2
      namespace: default
    spec:
      nodeName: <NODE-2>
      containers:
        - name: block-volume-test
          image: ubuntu:xenial
          imagePullPolicy: IfNotPresent
          command: ["sleep", "36000"]
          volumeDevices:
            - devicePath: /dev/longhorn/testblk
              name: block-vol
      volumes:
        - name: block-vol
          persistentVolumeClaim:
            claimName: longhorn-block-vol
    ```
1. Observe that volume engine is available on node-2. Volume is NOT detach during this process
1. Delete pod-1.
1. Observe that volume detached from node-1 but still attaching to node-2 throughout the whole process.
1. Exec into pod-2 and verify checksum matches `dd if=dev/longhorn/testblk bs=1M count=100 | md5sum`

### Auto attachment

**Comment by PhanLe1010** [comment]
## Test live migration on Harvester deployment

**Comment by PhanLe1010** [comment]
# Test Plan
(In progress...)
  
1. [Attachment interruption](https://github.com/longhorn/longhorn/issues/3715#issuecomment-1558076675)
1. [Test Upgrade](https://github.com/longhorn/longhorn/issues/3715#issuecomment-1562305097)
1. [Test live migration on Harvester deployment](https://github.com/longhorn/longhorn/issues/3715#issuecomment-1563637065)

**Comment by PhanLe1010** [comment]
## Test basic

### Test UI

### Test CSI
1. RWO
2. RWX

### Test CSI snapshot flow

### Test recurring job

### Test Restore/DR

### Test eviction

### Test exporting backing image from volume

### Test online/offline expansion 

### Test cloning

**Comment by yangchiu** [comment]
@PhanLe1010 
The following test item of `Test basic - Test UI` fails on `master-head`:
```
Test attach/detach volume using UI in normal/maintenance mode
```
After attached a volume using UI, it's unable to detach the volume using UI, because UI sent a detach request with `attachmentID = "longhorn-ui"`, but what the volume expects to is `attachmentID = ""`.

**Comment by PhanLe1010** [comment]
@yangchiu I just double checked and it seems working. The UI should sends attach request with `attachmentID = "longhorn-ui"` in the first place. Maybe `attachmentID = ""` is left over by something else. Could you retry with a fresh version of master-head OR an upgrade from v1.4.2 to master-head?

**Comment by yangchiu** [comment]
attach/detach volume will fail on volume list page:
![Screenshot from 2023-06-05 09-15-49](https://github.com/longhorn/longhorn/assets/5709208/ce77b1d1-9e7d-48ef-9195-6df124b82c74)
I've commented in https://github.com/longhorn/longhorn/issues/6004#issuecomment-1576035152. Let's follow up on that ticket.

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager 73dab70, longhorn-ui e6cc645) following [the test plan](https://github.com/longhorn/longhorn/issues/3715#issuecomment-1563637861).

**Comment by yangchiu** [comment]
For the [live migration](https://github.com/longhorn/longhorn/issues/3715#issuecomment-1563637065) item, @PhanLe1010 suggests:
> we should try to test with Harvester at least one time. KubeVirt has some logic to handle the migration that we cannot manually simulate.

So reopen this. But it needs extra time to figure how to setup Harvester environment. I'll revisit this after verified other ready-for-testing items and/or release testing items.

cc @innobead

**Comment by yangchiu** [comment]
Setup a 2-nodes `Harvester v1.1.2` (`rke2 v1.24.11`) cluster. After upgraded Longhorn from `v1.3.2` to `v1.4.2`, and then to `master`, `longhorn-manager` is stuck in `CrashLoopBackOff` forever with error messages like:
```
time="2023-06-08T07:00:44Z" level=warning msg="Failed to get webhook health endpoint https://localhost:9502/v1/healthz" error="Get \"https://localhost:9502/v1/healthz\": dial tcp [::1]:9502: connect: connection refused"
```
and no vm can be created for migration. But if I downgraded Longhorn back to `v1.4.2`, everything works again.

@PhanLe1010 Do you have any suggestion? Thanks!

**Comment by yangchiu** [comment]
Per @innobead 's suggestion, testing live migration with standalone Longhorn is good enough for now. But how to customize Longhorn in Harvester environment can be tackled later.

@PhanLe1010 @khushboo-rancher It would be appreciated that you can share some experience or knowledge about the environment setup.
I used the following approach: After Harvester ipxe installation and formed a 2-nodes cluster, I ssh into the control plane node and directly run `kubectl apply -f longhorn.yaml` to upgrade Longhorn. 
Correct me if it's the wrong way, or it's also appreciated that you can share if there's any pitfall needed to pay attention to. Many thanks!

**Comment by liyimeng** [comment]
We recently experienced a problem that can be take note  here:  we get a power of death of the entire cluster, when it is power on again, we see some volumenattachment is leftover, but Kubernetes schedule pod into anther node. Longhorn report error say that volume is already attached in old node.

**Comment by PhanLe1010** [comment]
> We recently experienced a problem that can be take note here: we get a power of death of the entire cluster, when it is power on again, we see some volumenattachment is leftover, but Kubernetes schedule pod into anther node. Longhorn report error say that volume is already attached in old node.

Please update us if you still see the problem in v1.5.0 (when it comes out). Many thanks
