### ISSUE TITLE
[TASK] Longhorn SPDK: add stop volume and replica functionality

### ISSUE THREAD

**Issue by keithalucas** [longhorn/longhorn#4058]
## What's the task? Please describe

During implementing https://github.com/longhorn/longhorn/issues/3871, there were something lacking in longhorn SPDK that need to be implemented in order to complete 3871 as written.

## Describe the items of the task (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [x] Update longhorn's SPDK repo to use a newer, fixed version of the official SPDK.  Test that it builds with a couple different distribution after the update.
- [x] Create a stop volume command.  It should wait until all pending I/O is completed and stop the NVMe-oF bdevs associated with the remote replica.   
- [x] Create a stop replica command.  It should stop making the replica available over NVMe-oF so we can remove the logical volume store.
- [x] Improve the bdev_longhorn_get_bdevs command to report information like bdev_get_bdevs.
- [ ] Improve the handling of IP addresses.   When a replica is remote, I need to set up a TCP NVMe-oF transport and a JSON-RPC listener on an IP address, this could be made more transparent.
- [ ] A command to get a list of a remote replica's snapshots in order to make one available over NVMe-oF to validate its content in a test.

The goal is to be able to reset a running SPDK instance, i.e. to remove the existing longhorn volumes and replicas created temporarily for a test in order to proceed to the next test without restarting.  It's also relevant to longhorn because SPDK will be a long-living process with volumes and replicas being started and stopped over its lifetime.

**Comment by innobead** [comment]
Closing, we will reorganize SPDK issues.
