### ISSUE TITLE
[FEATURE] Replica rebuild over SPDK

### ISSUE THREAD

**Issue by DamiaSan** [longhorn/longhorn#5216]
When a new replica has to be added or a replica has to be rebuilt, we have to recreate the entire snapshot stack of each volume that are hosted on that node.

Development to be made are the following:

- [x] shallow copy of a logical volume over an arbitrary bdev (that in our case will represent a remote volume exported via NVMe-oF and locally attached) #5217 
- [x] set the quality of service rate limit over shallow copy (there is already `bdev_set_qos_limit` in SPDK)
- [x] change parent of a logical volume #5866
- [x] introduce write only mode in RAID1 #5783 
- [x] Add a brand new/empty bdev with WriteOnly mode to the RAID1 bdev #5865
- [x] Snapshot & IO pause when adding the new WriteOnly bdev: https://github.com/longhorn/longhorn/issues/5421
- [ ] RW bdev inconsistency detection, which can trigger the rebuilding. https://github.com/longhorn/longhorn/issues/5422

cc @longhorn/dev-data-plane

**Comment by innobead** [comment]
Moving to the `Analysis and Design` pipeline, because @DamiaSan is working on this.

**Comment by innobead** [comment]
cc @shuo-wu

**Comment by shuo-wu** [comment]
As we already discussed, we need to add 2 more items/blockers for the rebuild:
- [ ] Add a brand new/empty bdev with WriteOnly mode to the RAID1 bdev
- [ ] Snapshot & IO pause when adding the new WriteOnly bdev: https://github.com/longhorn/longhorn/issues/5421
- [ ] RW bdev inconsistency detection, which can trigger the rebuilding.

**Comment by DamiaSan** [comment]
What about the set the quality of service rate limit over shallow copy, inside SPDK there is the RPC `bdev_set_qos_limit`. We can directly call this RPC over the bdev that acts as destination in the shallow copy. But due to how shallow copy status is actually implemented, all goes fine if this destination bdev is used, over the node where we call shallow copy, only in one point, i.e. only for the shallow copy. Otherwise some concurrency issue could happen. @shuo-wu do you think this can be acceptable? I think so, because this bdev is created over that node only for the shallow copy. Otherwise I should put some lock around the shallow copy status fields in blobstore.

**Comment by shuo-wu** [comment]
@DamiaSan Sorry, which one are you talking about? RW bdev inconsistency detection?
This is for one important issue: When we use several bdevs (including remote bdevs) to construct a RAID1 bdev, we need to make sure each base bdev hold the same data **and the same snapshot chian/tree**. IIUC, SPDK won't be responsible for it. Hence Longhorn may need to get the snapshot chain of each base bdev then makes sure all are identical. Here, when comparing each snapshot, we need **something like checksum** to validate data consistency.

**Comment by shuo-wu** [comment]
> this destination bdev is used only for the shallow copy right?

YES. 

I am thinking if setting qos rate limit is necessary. It's hard to know the performance of the cluster/nodes. Adding such kinds of config may slow down the rebuilding and waste the resource sometimes. cc @derekbit

**Comment by derekbit** [comment]
> > this destination bdev is used only for the shallow copy right?
> 
> 
> 
> YES. 
> 
> 
> 
> I am thinking if setting qos rate limit is necessary. It's hard to know the performance of the cluster/nodes. Adding such kinds of config may slow down the rebuilding and waste the resource sometimes. cc @derekbit 

I think it is not a priority as well, but we can add it later if users have feedback for it.

**Comment by DamiaSan** [comment]
Ok, perfect, this was my idea too. Using directly `bdev_set_qos_limit` over the destination bdev will not require any additional development over shallow copy.

**Comment by shuo-wu** [comment]
Sure. If later on users complain about the recourse consumption taken by rebuilding/shallow copy, we can add it quickly.

**Comment by innobead** [comment]
Online rebuilding will be tracked at #7199 
Delta rebuilding will be tracked at #5573 

cc @longhorn/dev-data-plane
