### ISSUE TITLE
[TEST] Introduce Negative Testing

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5240]
## What's the test to develop? Please describe

A clear and concise description of what the test you want to develop.

## Describe the items of the test development (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] `item 1`

## Additional context

Add any other context or screenshots about the test request here.

**Comment by innobead** [comment]
@khushboo-rancher feel free to update this task description, so we can plan it accordingly. 

cc @longhorn/qa

**Comment by innobead** [comment]
Moved this from 1.5.0, but follow this on QA board instead.

**Comment by innobead** [comment]
The current status is @yangchiu is working on the framework part with some example test case implementation. When they are ready and get merged, we will start the remaining case implementation based on priority. 

cc @nitendra-suse @chriscchien @roger-ryao @khushboo-rancher

**Comment by innobead** [comment]
@yangchiu I feel the description of this issue is outdated. Please help keep this up-to-date and refer the related issues to this EPIC. 

If need a separate epic, go ahead to create it. 

cc @khushboo-rancher

**Comment by innobead** [comment]
@yangchiu remember to update the description of this ticket, as discussed.

**Comment by yangchiu** [comment]
> @yangchiu remember to update the description of this ticket, as discussed.

I find I've updated it before. Read through the [ticket description](https://github.com/longhorn/longhorn/issues/5240#issue-1525060396), I think it's quite clear, and the newly created ticket https://github.com/longhorn/longhorn/issues/7211 is also recorded.

**Comment by innobead** [comment]
Great. Thanks.

**Comment by yangchiu** [comment]
**Tickets for each negative factor:**

- [x] [Investigate Node Reboot related operations for negative testing](https://github.com/longhorn/longhorn/issues/6499)
- [x] [Investigate Networking related operations for negative testing](https://github.com/longhorn/longhorn/issues/6704)
- [x] [Investigate CPU and Memory related operations for negative testing](https://github.com/longhorn/longhorn/issues/6705)
- [x] [Investigate IO and Filesystem related operations for negative testing](https://github.com/longhorn/longhorn/issues/6706)
- [x] [Investigate Cluster related operations for negative testing](https://github.com/longhorn/longhorn/issues/6707)
- [x] [Investigate qemu/kvm VM related operations for negative testing](https://github.com/longhorn/longhorn/issues/6708)
- [x] [Investigate VM snapshot operation for negative testing](https://github.com/longhorn/longhorn/issues/10918)

**Comment by yangchiu** [comment]
> [@longhorn/qa](https://github.com/orgs/longhorn/teams/qa) is this finished?

No, as mentioned in the description and the comment, the following items are not implemented yet:

**Tickets for each negative factor:**
- [x] [Investigate qemu/kvm VM related operations for negative testing](https://github.com/longhorn/longhorn/issues/6708)

**Longhorn operation:**
- [x] Clone volume
- [x] Upgrade longhorn
- [x] Replica Affinity
- [x] CSI Snapshot/Backup

**Negative factor:**
- [X] Reboot volume node
  - Only implemented in aws and hal. It's still todo in qemu/kvm.
- [X] Reboot replica node
  - Only implemented in aws and hal. It's still todo in qemu/kvm.
- [X] High latency API server
  - Only tested in aws. Need to review if it works in hal.
- [x] Introduce network latency on all nodes
  - Only tested in aws. Need to review if it works in hal.
- [x] Disconnect network of all nodes
  - Only tested in aws. Need to review if it works in hal.
- [x] Take snapshots on VM
    - Not implemented yet in aws, hal and qemu/kvm.

**Sub-tasks of this ticket:**
- [x] Implement each **Negative factor**
  - The above negative factors are not implemented yet.
- [x] Consider the real issues encountered, implement corresponding **Longhorn operation** and combine with **Negative factor** to create the automated negative test case and execute it to reproduce issues
  - The above Longhorn operations are not implemented yet.
- [ ] Automate manual test items in release testing: https://github.com/longhorn/longhorn/issues/7211
  - There are still test cases to be automated in the ticket.
- [x] Prepare long-running (local lab) test environment
  - The stability of connecting HAL behind VPN is still being tested.

cc @innobead @derekbit

**Comment by yangchiu** [comment]
Negative factors and Longhorn basic operations listed in this ticket have all been implemented. The remaining tasks for automating existing manual test items can be tracked in https://github.com/longhorn/longhorn/issues/7211.
