### ISSUE TITLE
[FEATURE] Support v2 Data Engine (GA)

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#6229]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

This epic aims to bring the v2 data engine to GA to support feature parity with the v1 data engine and facilitate live upgrades. This will involve supporting the underlying SPDK modules and the SPDK gRPC server, and enhancing the Instance Manager and Longhorn Manager, along with refactoring efforts across releases.

## Describe the solution you'd like

The related sub-issues will be created and added to this epic via Zenhub. 

- [x] Volume Live Upgrade - Data plane (1.7)
- [x] Online replica rebuilding (1.7)
- [X] TRIM (1.7)
- [x] Delta replica rebuilding via snapshot checksum (1.8)
- [x] Snapshot checksum (*1.8)
- [x] Volume Live Migration (1.8)
- [x] Backing image (1.8)
- [x] Volume Live Upgrade - Control Plane (1.13.0)
- [x] Disaster Recovery Volume (1.9)
- [x] Zero-copy/Fast Clone (1.12.1)
- [x] Volume Expansion (1.10)
- [x] Volume Encryption (1.8)
- [x] Delta replica rebuilding via delta snapshot (1.10)
- [x] Volume granular setting parity for V2 to match V1 data engine (1.10)

## Additional context

cc @longhorn/dev-data-plane

**Comment by innobead** [comment]
1.6 will be still preview with some new features introduced, so 1.7 will be an experimental version instead.

**Comment by innobead** [comment]
Moved this to 1.9.0, as all primary items should be ready in 1.9. cc @derekbit

**Comment by innobead** [comment]
Moving to v1.10, because some mandatory parts have been relocated to 1.10.

cc @longhorn/tpm

**Comment by derekbit** [comment]
Completed! Thanks @longhorn/dev and @longhorn/qa 
cc @innobead
