### ISSUE TITLE
[INFRA] Configurable infra set up for running chaos testing

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#6512]
## What's the test to develop? Please describe

We need to have an infra where we can control the spec like network bandwidth, disk iops etc

## Describe the items of the test development (DoD, definition of done) you'd like

- [ ] We can create similar setup like our current CI where we should be able to configure what should be the spec on nodes. For example, if configured with low network bandwidth between the nodes, this infra should use tools like `tc` to restrict the network bandwidth.
- [ ] The infra should be able to control one or multiple spec at the same time.
- [ ] The infra should be setup in such a way that our negative test cases should be able to run on it.
- [ ] All the configuration should be respected when a interruption like node reboot etc happens.
