### ISSUE TITLE
[TASK] Investigate if we can automate the Rancher chart release

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#7023]
## Task 1

At the moment, we need to follow [the instruction ](https://confluence.suse.com/display/LON/How+to+create+Rancher+Chart+PRs) to manually generate Rancher chart and create PR.

We would like to investigate if it can be automated. I.e., create a script to generate the Rancher chart.

## Task 2:

Investigate how to automate retrieve images from Helm charts https://github.com/rancher/image-mirror/pull/504#issuecomment-1782458653

**Comment by PhanLe1010** [comment]
Summited upstream PR improvements:

- [ ] https://github.com/rancher/image-mirror/issues/541
- [ ]

**Comment by PhanLe1010** [comment]
Investigation update:

### Task 1

> At the moment, we need to follow [the instruction ](https://confluence.suse.com/display/LON/How+to+create+Rancher+Chart+PRs) to manually generate Rancher chart and create PR.
> We would like to investigate if it can be automated. I.e., create a script to generate the Rancher chart.

After investigate, I think the current [the instruction ](https://confluence.suse.com/display/LON/How+to+create+Rancher+Chart+PRs) generate Rancher chart is already optimal. Most of the steps there are checking/finding/verifying that the new chart is referencing the correct commit/have correct Rancher chart prefix version. It is recommended process from Rancher team as well. 


### Task 2

> Investigate how to automate retrieve images from Helm charts https://github.com/rancher/image-mirror/pull/504#issuecomment-1782458653

Yes, we can achieve this automation. I submitted PRs to upstream, once it is merged, Longhorn team will not have to create PR to mirror Longhorn image into Rancher docker account. I.e., we will not have to create PRs similar to this anymore https://github.com/rancher/image-mirror/pull/504

**Comment by PhanLe1010** [comment]
### Test plan:

Make sure that when Longhorn release a new version, there is a PR automatically being created to mirror Longhorn image into Rancher docker account. For example, a PR similar to this one but for Longhorn images https://github.com/rancher/image-mirror/pull/535

**Comment by PhanLe1010** [comment]
Moving back to 1.6.0 because the upstream PRs are making progress and might be merged soon:
- [x] https://github.com/rancher/image-mirror/issues/541
- [ ] https://github.com/rancher/image-mirror/issues/543

**Comment by PhanLe1010** [comment]
cc @mantissahz From now on we don't need to mirror the images when create PR for Rancher chart

**Comment by innobead** [comment]
@PhanLe1010 What we achieved here is about image-mirror PR automation w/o chart PR, correct?

**Comment by PhanLe1010** [comment]
> @PhanLe1010 What we achieved here is about image-mirror PR automation w/o chart PR, correct?

You are correct! We wont have to manually create PR like this anymore https://github.com/rancher/image-mirror/pull/504

We still need to create Rancher chart PR as before because I think the steps is already optimized https://github.com/longhorn/longhorn/issues/7023#issuecomment-1869823474

**Comment by innobead** [comment]
Sounds good. If those steps for chart generation have been tuned, then we are good for the automation later.

**Comment by innobead** [comment]
Assigned to @mantissahz , close this after releasing the Rancher chart.

**Comment by mantissahz** [comment]
Hi @PhanLe1010,

Could you check this issue when you are available?
Images are not mirrored because of the [unauthorized issue](https://github.com/rancher/image-mirror/actions/runs/10919337304/job/30306768564).
This blocks the images from being mirrored.

**Comment by roger-ryao** [comment]
> Assigned to [@mantissahz](https://github.com/mantissahz) , close this after releasing the Rancher chart.


> Moving back to 1.6.0 because the upstream PRs are merged:
> 
> * [x]  [Fix bug which crash the script retrieve-image-tags.py rancher/image-mirror#542](https://github.com/rancher/image-mirror/pull/542)[x]  [[Improvement] Add a new data source, github-tagged-images-file, to automate retrieving images from a image-list file of a GitHub release rancher/image-mirror#544](https://github.com/rancher/image-mirror/pull/544)

After the related PRs have been merged, we can see that related PRs will be created automatically.  https://github.com/rancher/image-mirror/pulls?q=is%3Apr+is%3Aclosed+Added+image%28s%29+longhornio%2Fbacking-image-manager%3A

If there are no issues, I will go ahead and close this. If there are any problems, please feel free to reopen it.

cc @mantissahz  @PhanLe1010 @derekbit
