### ISSUE TITLE
[FEATURE] Support volume encryption for (encrypted) backing image volumes

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#7051]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

Currently, Longhorn supports non-backing image volume encryption, and it is impossible to enable volume encryption for an unencrypted backing image. The goal here is to support volume encryption regardless of whether the volume is based on a backing image or not, with the potential condition being that the backing image is also encrypted using the same crypto key.

ref: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#how-ebs-encryption-works

> Encrypt unencrypted resources
> You cannot directly encrypt existing unencrypted volumes or snapshots. However, you can create encrypted volumes or snapshots from unencrypted volumes or snapshots. If you enable encryption by default, Amazon EBS automatically encrypts new volumes and snapshots using your default KMS key for EBS encryption. 

ref: https://gitlab.com/cryptsetup/cryptsetup/-/wikis/FrequentlyAskedQuestions

> * **2.5 Can I encrypt an existing, non-empty partition to use LUKS?**
> 
> There is no converter, and it is not really needed. The way to do this is to make a backup of the device in question, securely wipe the device (as LUKS device initialization does not clear away old data), do a luksFormat, optionally overwrite the encrypted device, create a new filesystem and restore your backup on the now encrypted device. Also refer to sections "Security Aspects" and "Backup and Data Recovery".
> 

## Describe the solution you'd like

When creating a first snapshot from the backing image, should be encrypted first.

**Comment by ChanYiLin** [comment]
## Experiments

### Create Encrypted Volume with BackingImage
1. Create StorageClass with BackingImage and Encryption Info
    ```
    kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: longhorn-crypto-global
    provisioner: driver.longhorn.io
    allowVolumeExpansion: true
    parameters:
      numberOfReplicas: "3"
      staleReplicaTimeout: "2880" # 48 hours in minutes
      fromBackup: ""
      encrypted: "true"
      backingImage: "parrot"
      backingImageDataSourceType: "download"
      backingImageDataSourceParameters: '{"url": "https://longhorn-backing-image.s3-us-west-1.amazonaws.com/parrot.raw"}'
      csi.storage.k8s.io/provisioner-secret-name: "longhorn-crypto"
      csi.storage.k8s.io/provisioner-secret-namespace: "longhorn-system"
      csi.storage.k8s.io/node-publish-secret-name: "longhorn-crypto"
      csi.storage.k8s.io/node-publish-secret-namespace: "longhorn-system"
      csi.storage.k8s.io/node-stage-secret-name: "longhorn-crypto"
      csi.storage.k8s.io/node-stage-secret-namespace: "longhorn-system"
    ```
2. Create PVC from the StorageClass
    ```
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: longhorn-backing-image-pvc
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: longhorn-crypto-global
      resources:
        requests:
          storage: 5Gi
    ```
3. Create Pod using the Volume
    ```
    apiVersion: v1
    kind: Pod
    metadata:
      name: longhorn-simple-pod
      namespace: default
    spec:
      nodeSelector:
        kubernetes.io/hostname: kworker1
      restartPolicy: Always
      containers:
        - name: ubuntu
          image: ubuntu:22.04
          imagePullPolicy: IfNotPresent
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          volumeMounts:
            - name: vol
              mountPath: /data
          ports:
            - containerPort: 80
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: longhorn-backing-image-pvc
    ```
4. **Failed**
    Got error message
    ```
    Warning  FailedMount             14s (x7 over 46s)  kubelet                  MountVolume.MountDevice failed for volume "pvc-be8862f6-7b95-42dc-8067-0d3985cb757c" : 
    rpc error: code = InvalidArgument desc = unsupported disk encryption format unknown data, probably partitions
    ```

**Comment by ChanYiLin** [comment]
## Experiments

### Create Encrypted Volume with Encrypted BackingImage - **SUCCEEDED**
1. Create a Encrypted Volume `VolumeA` first
2. Write some data
3. Export the Volume to BackingImage `BackingImageA`
4. Create StorageClass with `BackingImageA` and Encryption Info
    ```
    kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: longhorn-crypto-global-export
    provisioner: driver.longhorn.io
    allowVolumeExpansion: true
    parameters:
      numberOfReplicas: "3"
      staleReplicaTimeout: "2880" # 48 hours in minutes
      fromBackup: ""
      encrypted: "true"
      backingImage: "parrot-encrypt"
      backingImageDataSourceType: "export-from-volume"
      csi.storage.k8s.io/provisioner-secret-name: "longhorn-crypto"
      csi.storage.k8s.io/provisioner-secret-namespace: "longhorn-system"
      csi.storage.k8s.io/node-publish-secret-name: "longhorn-crypto"
      csi.storage.k8s.io/node-publish-secret-namespace: "longhorn-system"
      csi.storage.k8s.io/node-stage-secret-name: "longhorn-crypto"
      csi.storage.k8s.io/node-stage-secret-namespace: "longhorn-system"
    ```
5. Create the PVC from the StorageClass
6. Create Pod using the PVC
7. **Successfully Mounted**

**Comment by ChanYiLin** [comment]
## Other Reference

### AWS
AWS supports following three scenarios: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIEncryption.html
- Encrypt a volume during launch
    - In this example, an AMI backed by an unencrypted snapshot is used to launch an EC2 instance with an encrypted EBS volume.
- Re-encrypt a volume during launch
    - In this example, an AMI backed by an encrypted snapshot is used to launch an EC2 instance with an EBS volume encrypted by a new KMS key.
- Change encryption state of multiple volumes during launch
    - In this more complex example, an AMI backed by multiple snapshots (each with its own encryption state) is used to launch an EC2 instance with a newly encrypted volume and a re-encrypted volume.


### Ceph
- Ceph supports encrypt the rdb image: https://docs.ceph.com/en/quincy/rbd/rbd-encryption/

**Comment by ChanYiLin** [comment]
## Experiments

### Manually Encrypt a Non-encrypted Raw Backing Image - **SUCCEEDED**

- Create a BackingImage with testing raw image 
    - `https://longhorn-backing-image.s3-us-west-1.amazonaws.com/parrot.raw`
    -  32MB
- Login to the host and cd to `/var/lib/longhorn/backing-images/parrot-cd8eb5b3/`
- Truncate an empty image
    - `$ truncate -s 48M backing-encrypted`
- Setup the loop device
    - `$ losetup /dev/loop7 backing-encrypted`
- Format the device with `cryptsetup`
    - `$ echo -n "Your encryption passphrase" | cryptsetup -q luksFormat --type luks2 --cipher aes-xts-plain64 --hash sha256 --key-size 256 --pbkdf argon2i /dev/loop7 -`
- Open the encrypted device
    - `$ echo -n "Your encryption passphrase" | cryptsetup luksOpen /dev/loop7 backing-encrypted -`
- Dump the original data to the encrypted device
    - `$ dd if=backing of=/dev/mapper/backing-encrypted`
- Create another BackingImage with the new image file `backing-encrypted`
    - Type: Upload 
- Create StorageClass with the same secret key
    ```
    apiVersion: v1
    kind: Secret
    metadata:
      name: longhorn-crypto
      namespace: longhorn-system
    stringData:
      CRYPTO_KEY_VALUE: "Your encryption passphrase"
      CRYPTO_KEY_PROVIDER: "secret"
      CRYPTO_KEY_CIPHER: "aes-xts-plain64"
      CRYPTO_KEY_HASH: "sha256"
      CRYPTO_KEY_SIZE: "256"
      CRYPTO_PBKDF: "argon2i"

    ---

    kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: longhorn-parrot-encrypted
    provisioner: driver.longhorn.io
    allowVolumeExpansion: true
    parameters:
      numberOfReplicas: "2"
      staleReplicaTimeout: "2880" # 48 hours in minutes
      fromBackup: ""
      encrypted: "true"
      backingImage: "parrot-encrypted"
      backingImageDataSourceType: "upload"
      csi.storage.k8s.io/provisioner-secret-name: "longhorn-crypto"
      csi.storage.k8s.io/provisioner-secret-namespace: "longhorn-system"
      csi.storage.k8s.io/node-publish-secret-name: "longhorn-crypto"
      csi.storage.k8s.io/node-publish-secret-namespace: "longhorn-system"
      csi.storage.k8s.io/node-stage-secret-name: "longhorn-crypto"
      csi.storage.k8s.io/node-stage-secret-namespace: "longhorn-system"
    ```
- Create the PVC
    ```
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: longhorn-volume-parrot-encrypted
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: longhorn-parrot-encrypted
      resources:
        requests:
          storage: 5Gi
    ```
- Create the Pod with the encrypted Volume
    ```
    apiVersion: v1
    kind: Pod
    metadata:
      name: longhorn-simple-pod
      namespace: default
    spec:
      nodeSelector:
        kubernetes.io/hostname: kworker1
      restartPolicy: Always
      containers:
        - name: ubuntu
          image: ubuntu:22.04
          imagePullPolicy: IfNotPresent
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          volumeMounts:
            - name: vol
              mountPath: /data
          ports:
            - containerPort: 80
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: longhorn-volume-parrot-encrypted
    ```

### Results
- The pod can mount the volume
- The data content is the same as the original
- The device is encrypted

**Comment by ChanYiLin** [comment]
### TODO
- [] LEP: https://github.com/longhorn/longhorn/pull/8740
- [] longhorn-manager PR: https://github.com/longhorn/backing-image-manager/pull/251
- [] backing-image-manager PR: https://github.com/longhorn/longhorn-manager/pull/2876
- [] longhorn CRD PR: TBD
- [] generate longhorn manager API client: TBD

**Comment by roger-ryao** [comment]
**Verified on master-head 20240708**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/e5a1b586b8ea3fb70652af89359aa6dbe4aaddd6
- backing-image-manager `master-head` https://github.com/longhorn/backing-image-manager/commit/dfbe0d008b9c1cdb8e4780681454553bd5cd56e7
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/754a93e3ee86bbfcb0325c96d2666b1422556daf
- longhorn-ui `master-head` https://github.com/longhorn/longhorn-ui/commit/546becd1b42df5aa6a5b5a0ede45abae2a0153b4

**The test steps**
https://github.com/longhorn/longhorn/issues/7051#issuecomment-2177330536


**Result passed**

Testing Items via `CRD` and `UI`

- [x] Raw Image Encryption
  1. Create an encrypted backing Image `parrot-cloned-encrypted` cloned from `parrot.raw`
  2. Decrypt the Encrypted BackingImage `parrot-cloned-decrypt` from `parrot-cloned-encrypted`
  3. Clone Backing Image from `parrot.raw`
- [x] QCOW2 Image Encryption
  1. Create an encrypted backing Image `parrot-cloned-encrypted` clone from `parrot.qcow2`
  2. Decrypt the Encrypted BackingImage `parrot-cloned-decrypt` from `parrot-cloned-encrypted`
  3. Clone Backing Image from `parrot.qcow2`
- [x] require/lep
  - https://github.com/longhorn/longhorn/pull/8740
- [x] require/ui
  - https://github.com/longhorn/longhorn/issues/8789
- [x] require/auto-e2e-test
  - https://github.com/longhorn/longhorn/issues/7052
- [x] require/doc
  - https://github.com/longhorn/website/pull/927
