### ISSUE TITLE
[IMPROVEMENT] Improve environment_check script for NFS protocol bug and the host system self diagnosis 

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7931]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

The objective of the improvement is to 
- [x] Update the [KB doc](https://longhorn.io/kb/troubleshooting-rwx-volume-fails-to-attached-caused-by-protocol-not-supported/) for the NFS bug in kernel 5.15.0-94 ([ref](https://github.com/longhorn/longhorn/issues/6887#issuecomment-1946268547))  
- [x] Update environment_check script for checking kernel versions ([ref](https://github.com/longhorn/longhorn/issues/6887#issuecomment-1946268547))  
- [x] ~~Add condition(s) in `node.status.conditions` to check the environment, like the kernel version~~
  - ~~After users update their system stuff like the host distro or kernel, they usually skip the environment check. To make it easier for them to spot any known environment problems, we can just run checks in the node controller and note down the status in `node.status.conditions`.~~
- [x] Add OS distro and kernel version to logging when mount fails.

**Comment by james-munson** [comment]
Looking at the [probable culprit change](https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/jammy/commit/?h=Ubuntu-5.15.0-94.104&id=b8bcda78d824e521d31300dd7b1f0766cd01ce91) and its [fix](https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/jammy/commit/?h=Ubuntu-5.15.0-100.110&id=e8104b224c3d60a0f384f6b38419523aed4912dd) it appears that this is an NFS v4.1 issue, but that is our default.

**Comment by derekbit** [comment]
Besides of the environment_check script, I'm considering adding a condition in node.status.conditions to check the environment, like the kernel version.
WDYT? @innobead @james-munson

**Comment by innobead** [comment]
Sounds good to me @derekbit . Let's update the requirements of this request.

**Comment by derekbit** [comment]
> Sounds good to me @derekbit . Let's update the requirements of this request.

Updated. Thank you.

**Comment by TropicLegend** [comment]
Is there currently a workaround?

**Comment by anultravioletaurora** [comment]
> Is there currently a workaround?

I think it might just be either downgrading to the .92 kernel release or wait for the .100 release

@derekbit Is that accurate?

**Comment by derekbit** [comment]
> > Is there currently a workaround?
> 
> I think it might just be either downgrading to the .92 kernel release or wait for the .100 release
> 
> @derekbit Is that accurate?

Yes, totally right!

**Comment by TropicLegend** [comment]
Thank you, downgrading indeed solved the problem. 👍

**Comment by innobead** [comment]
@james-munson remember to update the zenhub status.

**Comment by james-munson** [comment]
May need to update the `fixed` and `broken` versions.  I see in https://github.com/longhorn/longhorn/issues/6857#issuecomment-1821416051 that 6.5.8 is broken, but the fix came in or before 6.5.11.

**Comment by krohrsb** [comment]
Note that this issue happens to me on `5.15.0-1047-raspi`

**Comment by james-munson** [comment]
And also (reported in Slack) Ubuntu kernel `6.5.0-21-generic #21~22.04.1-Ubuntu`

**Comment by johnlaur** [comment]
> And also (reported in Slack) Ubuntu kernel `6.5.0-21-generic #21~22.04.1-Ubuntu`

I am tracking this same bug with NFS4 on vsphere-csi but can confirm that it exists in the current HWE kernels for 20.04, 22.04 and the current release kernels of 23.10 along with haphazardly most of the current versions of the variant kernels that I tested. Finding an affected kernel in any current Ubuntu release is like shooting fish in a barrel. The list extends to pretty much every variant they currently ship -- publishing a list of affected package versions without actually testing all the packaged kernels is going to lead to a lot more reports over the coming weeks as an Ubuntu system is more or less going to unavoidably upgrade to a broken kernel.

**Comment by amorabito** [comment]
I installed a .100 release tonight for Ubuntu. Seems to have resolved the issue on my end.

**Comment by Delta1977** [comment]
Here we same, .100 kernel solved it. Also the actual /new her-kernel (6.5) solves it.

**Comment by roger-ryao** [comment]
**Verified on master-head 20240625**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/7e01ba13b41dd74689da8ec9e474baaf91363acc

**The test steps**
https://github.com/longhorn/longhorn/issues/7931#issuecomment-1953534962

**Result Passed**

- [x] 1. Update the [KB doc](https://longhorn.io/kb/troubleshooting-rwx-volume-fails-to-attached-caused-by-protocol-not-supported/) for the NFS bug in kernel 5.15.0-94 ([ref](https://github.com/longhorn/longhorn/issues/6887#issuecomment-1946268547))  
- [x] 2. Update environment_check script for checking kernel versions ([ref]
(https://github.com/longhorn/longhorn/issues/6887#issuecomment-1946268547))  

- [ ] 3. Add OS distro and kernel version to logging when mount fails.

   I tried to create an RWX volume and mount it to a pod on problematic previous kernel versions locally, on AWS, and on DigitalOcean, but I couldn't reproduce the issue where the RWX volume fails to be attached. 
   (PS: The default kernel for `AWS Ubuntu 22.04` is **linux-image-6.5.0-1017-aws**, which fixes the issue.)
   Therefore, I couldn't verify the addition of OS distro and kernel version to logging when the mount fails.
