### ISSUE TITLE
[IMPROVEMENT] Check kernel module `dm_crypt` on host machines

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#9153]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

1. Add the necessary `dm_crypt` kernel module for encrypted volumes in the official document
2. Add the necessary `dm_crypt` kernel module check in the `node.status.conditions`
3. Add the necessary `dm_crypt` kernel module check in the `longhornctl`

## Additional context

https://github.com/longhorn/longhorn/issues/9135

## Tasks

- [x] doc: The documentation for the necessary `dm_crypt` kernel module for encrypted volumes
- [x] longhorn-manager: `dm_crypt` kernel module check in the `node.status.conditions`
- [x] cli: `dm_crypt` kernel module check

**Comment by derekbit** [comment]
We need to figure out how to check the built-in kernel module. Let's move it to v1.7.2 instead.

**Comment by roger-ryao** [comment]
**Verified on v1.8.0-dev-20240922 20231001**

- longhorn v1.8.0-dev-20240922 https://github.com/longhorn/longhorn/commit/ddfda37472d9b4d877c2a60663bb176ae3828825
- cli v1.8.0-dev-20240922 https://github.com/longhorn/cli/commits/v1.8.0-dev-20240922/

**The test steps**
https://github.com/longhorn/longhorn/issues/9153#issuecomment-2285974275

**Result**

1. Output when `dm_crypt` is not loaded:
```console
  warn:
  - multipathd.service is running. Please refer to https://longhorn.io/kb/troubleshooting-volume-with-multipath/ for more information.
ryao-demo-0926-w2-94f08d41-4tssf:
  error:
  - 'Module dm_crypt is not loaded: failed to execute: nsenter [--mount=/host/proc/1940366/ns/mnt --net=/host/proc/1940366/ns/net grep dm_crypt /proc/modules], output , stderr : exit status 1'
  info:
  - Service iscsid is running
  - NFS4 is supported
  - Package nfs-common is installed
  - Package open-iscsi is installed
  - Package cryptsetup is installed
```
Additionally, in the node's YAML:
```yaml
    - lastProbeTime: ""
      lastTransitionTime: "2024-09-30T02:55:13Z"
      message: Kernel modules [dm_crypt] are not loaded on node ryao-demo-0926-w3-57d499c4-2chfp
      reason: KernelModulesNotLoaded
      status: "False"
      type: KernelModulesLoaded
```

After running `longhornctl install preflight` and executing `longhornctl check preflight` again, you can see that `dm_crypt` has been successfully loaded.


```console
  - Module dm_crypt is loaded
```

The node's YAML is updated as well:
```yaml
    - lastProbeTime: ""
      lastTransitionTime: "2024-10-01T02:04:23Z"
      message: Kernel modules [dm_crypt] are loaded on node ryao-demo-0926-w3-57d499c4-2chfp
      reason: ""
      status: "True"
      type: KernelModulesLoaded
```

**Comment by c3y1huang** [comment]
Reopen this issue because we also need to update the document on [Root and Privileged Permission - Longhorn Manager](https://github.com/longhorn/website/blob/c4fa470afbf0fc55968020e1417ad40e230ce110/content/docs/1.8.0/deploy/install/_index.md?plain=1#L158-L161) about  https://github.com/longhorn/longhorn/pull/9374.

cc @derekbit

**Comment by roger-ryao** [comment]
> Reopen this issue because we also need to update the document on [Root and Privileged Permission - Longhorn Manager](https://github.com/longhorn/website/blob/c4fa470afbf0fc55968020e1417ad40e230ce110/content/docs/1.8.0/deploy/install/_index.md?plain=1#L158-L161) about #9374.
> 
> cc @derekbit

Close it due to https://github.com/longhorn/website/pull/1017 having been merged

**Comment by AkakievKD** [comment]
![Image](https://github.com/user-attachments/assets/380c39ba-2472-4ff8-8973-f06181088906)

**Comment by AkakievKD** [comment]
on 1 of 3 workers and i instance-manager recreating all time

**Comment by AkakievKD** [comment]
![Image](https://github.com/user-attachments/assets/d470a908-55b6-44a0-8862-2874d53c7d4d)

**Comment by derekbit** [comment]
@AkakievKD I don't think this is related to the node condition. It just records the status and won't stop any instance-manager pod. Please provide a support bundle for troubleshooting.
