### ISSUE TITLE
Feature: Notification support

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#928]
Longhorn needs a notification framework to notify user about events.

E.g.
- [ ] Email or Slack notification when the backup completes (#542)
- [x] Volume usage approaches the limit (#925)
- [x] Disk usage approaches the limit (#925)

**Comment by yasker** [comment]
All of those features should be covered by Prometheus alertmanager. Make sure we add documents for them.

**Comment by yasker** [comment]
Document has been merged at https://github.com/longhorn/website/commit/5f01450e80a28d80d2ec785f48b068671c59c65f .

We're using Prometheus Alert Manager for the notification.

Examples are available at https://github.com/longhorn/website/blob/v1.1.0/content/docs/1.1.0/monitoring/alert-rules-example.md .
